@campabuc.api_HostAddress = http://localhost:5217

GET {{campabuc.api_HostAddress}}/categories/
Accept: application/json
;
GET {{campabuc.api_HostAddress}}/shoes/
Accept: application/json
;
GET {{campabuc.api_HostAddress}}/manufacturers/
Accept: application/json
;
GET {{campabuc.api_HostAddress}}/categories/
Accept: application/json
;
GET {{campabuc.api_HostAddress}}/categories/
Accept: application/json
;
GET {{campabuc.api_HostAddress}}/categories/
Accept: application/json
;
###
