// <auto-generated />
using System;
using CamPabuc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CamPabuc.Infrastructure.Migrations
{
    [DbContext(typeof(CamPabucContext))]
    [Migration("20260513211139_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CamPabuc.Domain.Entity.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InfoType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("IX_ContactInfo_ContactId");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Bowerman Dr, Beaverton, OR",
                            CreatedAt = new DateOnly(2026, 5, 14),
                            IsActive = true,
                            Name = "Nike",
                            Phone = "555-0100",
                            UpdatedAt = new DateOnly(2026, 5, 14)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Adi-Dassler-Straße 1, Herzogenaurach",
                            CreatedAt = new DateOnly(2026, 5, 14),
                            IsActive = true,
                            Name = "Adidas",
                            Phone = "555-0200",
                            UpdatedAt = new DateOnly(2026, 5, 14)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Puma Way 1, Herzogenaurach",
                            CreatedAt = new DateOnly(2026, 5, 14),
                            IsActive = true,
                            Name = "Puma",
                            Phone = "555-0300",
                            UpdatedAt = new DateOnly(2026, 5, 14)
                        });
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.POItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShoeVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ShoeVariantId");

                    b.ToTable("POItems");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceAtSale")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShoeVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("ShoeVariantId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ShoeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShoeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2026, 5, 14),
                            IsActive = true,
                            Name = "Running",
                            UpdatedAt = new DateOnly(2026, 5, 14)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateOnly(2026, 5, 14),
                            IsActive = true,
                            Name = "Casual",
                            UpdatedAt = new DateOnly(2026, 5, 14)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateOnly(2026, 5, 14),
                            IsActive = true,
                            Name = "Formal",
                            UpdatedAt = new DateOnly(2026, 5, 14)
                        });
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ShoeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseMaterial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShoeCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ShoeCategoryId");

                    b.ToTable("ShoeModels");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ShoeVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShoeModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShoeModelId");

                    b.ToTable("ShoeVariants");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShoeVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShoeVariantId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ContactInfo", b =>
                {
                    b.HasOne("CamPabuc.Domain.Entity.Contact", "Contact")
                        .WithMany("ContactInfos")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.POItem", b =>
                {
                    b.HasOne("CamPabuc.Domain.Entity.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamPabuc.Domain.Entity.ShoeVariant", "ShoeVariant")
                        .WithMany()
                        .HasForeignKey("ShoeVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("ShoeVariant");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.PurchaseOrder", b =>
                {
                    b.HasOne("CamPabuc.Domain.Entity.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.SaleItem", b =>
                {
                    b.HasOne("CamPabuc.Domain.Entity.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CamPabuc.Domain.Entity.ShoeVariant", "ShoeVariant")
                        .WithMany()
                        .HasForeignKey("ShoeVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");

                    b.Navigation("ShoeVariant");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ShoeModel", b =>
                {
                    b.HasOne("CamPabuc.Domain.Entity.Manufacturer", "Manufacturer")
                        .WithMany("ShoeModels")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("CamPabuc.Domain.Entity.ShoeCategory", "ShoeCategory")
                        .WithMany("ShoeModels")
                        .HasForeignKey("ShoeCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("ShoeCategory");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ShoeVariant", b =>
                {
                    b.HasOne("CamPabuc.Domain.Entity.ShoeModel", "ShoeModel")
                        .WithMany("Variants")
                        .HasForeignKey("ShoeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoeModel");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.StockAdjustment", b =>
                {
                    b.HasOne("CamPabuc.Domain.Entity.ShoeVariant", "ShoeVariant")
                        .WithMany()
                        .HasForeignKey("ShoeVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoeVariant");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.Contact", b =>
                {
                    b.Navigation("ContactInfos");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.Manufacturer", b =>
                {
                    b.Navigation("ShoeModels");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ShoeCategory", b =>
                {
                    b.Navigation("ShoeModels");
                });

            modelBuilder.Entity("CamPabuc.Domain.Entity.ShoeModel", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
