CREATE TABLE manufacturers(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"name" VARCHAR(255) NOT NULL,
	address TEXT NULL,
	phone VARCHAR(20) NULL,
	contact_name VARCHAR(50) null,
	created_at TIMESTAMP NOT NULL DEFAULT(NOW()),
	updated_at TIMESTAMP NULL
)
