CREATE TABLE order_items(
	id UUID PRIMARY KEY,
	order_id UUID NOT NULL REFERENCES ORDERS(ID),
	item_id UUID NOT NULL REFERENCES SHOES(ID),
	quantity BIGINT NOT NULL DEFAULT(0),
	created_at TIMESTAMP NOT NULL DEFAULT(NOW()),
	updated_at TIMESTAMP NULL,
	status INT NULL
)
